package com.yuktiai.serviceimpl;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import com.yuktiai.service.CloudinaryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.Map;

@Service
@RequiredArgsConstructor
@Slf4j
public class CloudinaryServiceImpl implements CloudinaryService {

    private final Cloudinary cloudinary;

    @Override
    public String uploadFile(MultipartFile file) throws IOException {
        log.info("Uploading file to Cloudinary: {}", file.getOriginalFilename());
        Map<?, ?> uploadResult = cloudinary.uploader().upload(
                file.getBytes(),
                ObjectUtils.asMap(
                        "resource_type", "auto",
                        "folder", "resumes"
                )
        );
        String secureUrl = (String) uploadResult.get("secure_url");
        log.info("Cloudinary upload successful, secure URL: {}", secureUrl);
        return secureUrl;
    }

    @Override
    public String uploadBytes(byte[] bytes, String fileName) throws IOException {
        log.info("Uploading generated byte array to Cloudinary: {}", fileName);
        Map<?, ?> uploadResult = cloudinary.uploader().upload(
                bytes,
                ObjectUtils.asMap(
                        "resource_type", "auto",
                        "folder", "optimized_resumes",
                        "public_id", fileName.replaceAll("[^a-zA-Z0-9]", "_")
                )
        );
        String secureUrl = (String) uploadResult.get("secure_url");
        log.info("Cloudinary byte array upload successful, secure URL: {}", secureUrl);
        return secureUrl;
    }

    @Override
    public void deleteFile(String cloudinaryUrl) {
        if (cloudinaryUrl == null || cloudinaryUrl.isEmpty()) {
            return;
        }
        try {
            String publicId = extractPublicId(cloudinaryUrl);
            if (publicId != null) {
                log.info("Deleting file from Cloudinary: {}", publicId);
                cloudinary.uploader().destroy(publicId, ObjectUtils.emptyMap());
            }
        } catch (Exception e) {
            log.error("Failed to delete file from Cloudinary for URL: {}. Error: {}", cloudinaryUrl, e.getMessage());
        }
    }

    private String extractPublicId(String url) {
        try {
            int uploadIndex = url.indexOf("/upload/");
            if (uploadIndex == -1) {
                return null;
            }
            String sub = url.substring(uploadIndex + 8);
            if (sub.startsWith("v")) {
                int firstSlash = sub.indexOf("/");
                if (firstSlash != -1) {
                    sub = sub.substring(firstSlash + 1);
                }
            }
            int dotIndex = sub.lastIndexOf(".");
            if (dotIndex != -1) {
                sub = sub.substring(0, dotIndex);
            }
            return sub;
        } catch (Exception e) {
            log.error("Error parsing Cloudinary URL: {}", url, e);
            return null;
        }
    }
}
